import { AppError } from '../../shared/errors/app-error.js';
import { chunk, unique } from '../../shared/utils/collections.js';
import type { SpotifyClient } from '../../shared/spotify/client.js';
import type { AddPlaylistItemsInput, CreatePlaylistInput, Playlist, PlaylistUpdateResult, RemovePlaylistItemsInput, SpotifyPlaylist } from './types.js';

const mapPlaylist = (item: SpotifyPlaylist): Playlist => ({ id: item.id, name: item.name, description: item.description ?? '', public: item.public ?? null, collaborative: Boolean(item.collaborative), snapshotId: item.snapshot_id, totalItems: item.items?.total ?? item.tracks?.total ?? 0, uri: item.uri, externalUrl: item.external_urls?.spotify ?? null, owner: { id: item.owner?.id, displayName: item.owner?.display_name ?? null } });
export class PlaylistService {
  constructor(private readonly client: SpotifyClient, private readonly batchSize = 100) {}
  async currentUser(): Promise<any> { return this.client.fetch('/me'); }
  async listPlaylists(): Promise<Playlist[]> { return (await this.client.fetchAllPages<SpotifyPlaylist>('/me/playlists?limit=50')).map(mapPlaylist); }
  async getPlaylist(id: string): Promise<Playlist> { return mapPlaylist(await this.client.fetch(`/playlists/${encodeURIComponent(id)}`)); }
  async listItems(id: string): Promise<any[]> { return this.client.fetchAllPages(`/playlists/${encodeURIComponent(id)}/items?limit=50&additional_types=track,episode`); }
  async create(input: CreatePlaylistInput): Promise<Playlist> { if (!input.name.trim()) throw new AppError('INVALID_PLAYLIST_NAME', 'O nome da playlist é obrigatório.'); if (input.collaborative && input.public) throw new AppError('INVALID_PLAYLIST_VISIBILITY', 'Uma playlist colaborativa deve ser privada.'); return mapPlaylist(await this.client.fetch('/me/playlists', { method: 'POST', body: JSON.stringify({ name: input.name.trim(), description: input.description ?? '', public: input.public ?? false, collaborative: input.collaborative ?? false }) })); }
  async add(input: AddPlaylistItemsInput): Promise<PlaylistUpdateResult> { const uris = input.removeInputDuplicates ? unique(input.uris) : input.uris; return this.mutate(input.playlistId, uris, 'add'); }
  async remove(input: RemovePlaylistItemsInput): Promise<PlaylistUpdateResult> { return this.mutate(input.playlistId, unique(input.uris), 'remove', input.snapshotId); }
  private async mutate(playlistId: string, uris: string[], operation: 'add' | 'remove', snapshotId?: string): Promise<PlaylistUpdateResult> { let processed = 0; let batches = 0; let currentSnapshot = snapshotId; const groups = chunk(uris, this.batchSize); for (const [index, group] of groups.entries()) { try { const result = operation === 'add' ? await this.client.fetch<any>(`/playlists/${encodeURIComponent(playlistId)}/items`, { method: 'POST', body: JSON.stringify({ uris: group }) }) : await this.client.fetch<any>(`/playlists/${encodeURIComponent(playlistId)}/items`, { method: 'DELETE', body: JSON.stringify({ tracks: group.map((uri) => ({ uri })), ...(currentSnapshot ? { snapshot_id: currentSnapshot } : {}) }) }); processed += group.length; batches += 1; currentSnapshot = result.snapshot_id ?? currentSnapshot; } catch { return { playlistId, requested: uris.length, processed, failed: uris.length - processed, batchesProcessed: batches, snapshotId: currentSnapshot, failedBatch: index + 1, remainingUris: uris.slice(processed) }; } } return { playlistId, requested: uris.length, processed, failed: 0, batchesProcessed: batches, snapshotId: currentSnapshot }; }
}
