import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { sanitizeFileName, timestampForFile } from '../../shared/utils/files.js';
import type { PlaylistService } from '../playlists/playlist-service.js';

const url = (value: any) => value?.external_urls?.spotify ?? null;
export class ExportService {
  constructor(private readonly playlists: PlaylistService, private readonly outputDirectory: string) {}
  async playlistsToJson(): Promise<string> { const [user, playlists] = await Promise.all([this.playlists.currentUser(), this.playlists.listPlaylists()]); const body = { schemaVersion: '1.0', exportType: 'playlists', exportedAt: new Date().toISOString(), user: { id: user.id, displayName: user.display_name ?? null, spotifyUrl: url(user) }, total: playlists.length, playlists }; return this.write('playlists', `spotify-playlists-${timestampForFile()}.json`, body); }
  async playlistItemsToJson(playlistId: string): Promise<string> { const [playlist, items] = await Promise.all([this.playlists.getPlaylist(playlistId), this.playlists.listItems(playlistId)]); let ignoredEpisodes = 0, unavailableItems = 0, localTracks = 0, exportedTracks = 0; const mapped = items.map((item, position) => { const playlistItem = item.item ?? item.track; if (playlistItem?.type === 'episode') { ignoredEpisodes += 1; return null; } if (!playlistItem) { unavailableItems += 1; return { position, addedAt: item.added_at ?? null, addedBy: item.added_by ? { id: item.added_by.id ?? null, displayName: item.added_by.display_name ?? null } : null, track: null }; } const track = playlistItem; exportedTracks += 1; if (track.is_local) localTracks += 1; return { position, addedAt: item.added_at ?? null, addedBy: item.added_by ? { id: item.added_by.id ?? null, displayName: item.added_by.display_name ?? null } : null, track: { id: track.id ?? null, uri: track.uri ?? null, name: track.name, artists: (track.artists ?? []).map((a: any) => ({ id: a.id ?? null, name: a.name, uri: a.uri ?? null, spotifyUrl: url(a) })), album: track.album ? { id: track.album.id ?? null, name: track.album.name, uri: track.album.uri ?? null, releaseDate: track.album.release_date ?? null, spotifyUrl: url(track.album) } : null, durationMs: track.duration_ms ?? null, explicit: track.explicit ?? null, isLocal: Boolean(track.is_local), isPlayable: track.is_playable ?? null, spotifyUrl: url(track) } }; }).filter(Boolean); const body = { schemaVersion: '1.0', exportType: 'playlist-items', exportedAt: new Date().toISOString(), playlist, summary: { totalItems: items.length, exportedTracks, ignoredEpisodes, unavailableItems, localTracks }, items: mapped }; return this.write('playlist-items', `${sanitizeFileName(playlist.name)}-${timestampForFile()}.json`, body); }
  private async write(category: string, name: string, value: unknown): Promise<string> { const dir = join(this.outputDirectory, category); await mkdir(dir, { recursive: true }); const path = join(dir, name); await writeFile(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8'); return path; }
}
